### ISSUE TITLE
Error when Logging in 

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/LessonsApp#86] opened 2021-11-02 15:34 UTC
Several times this has happened I login as kbyrd@cedarridgecc.com and I get this error.Application error: "a client-side exception has occurred (see the browser console for more information)."

I had to refresh several times to get in

**Comment by mbyrdLCS** [comment] 2021-11-27 17:16
Application error: a client-side exception has occurred (see the browser console for more information). This Error is Happening again Sat Nov 27th I can not get in at all. I was finally able to get in by opening it up in a new Browser I think it has to do something with the cache 
![Screen Shot 2021-11-27 at 11 14 07 AM](https://user-images.githubusercontent.com/65249159/143690656-2d325c43-caca-4620-abcf-be20f798de4f.png)

**Comment by jzongker** [comment] 2022-01-05 14:41
@mbyrdLCS  Could you try again and let me know if the problem is still occurring?  I am unable to reproduce it today but there have been a number of changes to access API since this was originally reported.  Please close the issue for now if it does work ok.

**Comment by mbyrdLCS** [comment] 2022-01-05 15:10
I am Getting the Same Error Application  error: a client-side exception has occurred (see the browser console for more information). account mike@signpresenter.com

**Comment by jzongker** [comment] 2022-04-13 15:21
It appears this was fixed a while back.

**Closed by jzongker** 2022-04-13 15:21 UTC
Labels: bug, info needed, More info Provided
